### ISSUE TITLE
compute_node_list missing in Gen_Clust_New_AllLayers_Omp.py

### ISSUE THREAD

**Issue by friolero** [metro-smiles/CNN_Compression#1]
Hi! Thanks for the awesome work. 
I'm trying to understand the method from scripts. Seems there is no compute_node_list() function in Gen_Clust_New_AllLayers_Omp.py?  May I know what does the function do? Thanks!

**Comment by metro-smiles** [comment]
Hey,

Appreciate your comments.

It's my bad it should be omp_appx() instead. I've updated the repo, would you mind doing a fresh pull? 
Apologies for the inconvenience

**Comment by friolero** [comment]
No problem. Thanks a lot for fixing it!
